# Generated by Django 4.1.7 on 2023-04-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCelularUsado', '0002_inicio_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasenia',
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
