# Generated by Django 4.1.7 on 2023-04-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCelularUsado', '0003_remove_usuario_contrasenia_usuario_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenCelular',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
