# Generated by Django 4.1.7 on 2023-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCelularUsado', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=40),
        ),
    ]
